### ISSUE TITLE
KeyError: 'bevformer is not in the models registry'

### ISSUE THREAD

**Issue by Han-lim** [fundamentalvision/BEVFormer#117]
I tried to run your code as it is, but I got an error that 'bevformer is not in model registry.'
Do you know why this error occurs?

<Error message>
----------------
Traceback (most recent call last):
  File "./tools/train.py", line 270, in <module>
    main()
  File "./tools/train.py", line 223, in main
    model = build_model(
  File "/home/user/anaconda3/envs/bevformer/lib/python3.8/site-packages/mmdet3d-0.17.1-py3.8-linux-x86_64.egg/mmdet3d/models/builder.py", line 84, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/user/anaconda3/envs/bevformer/lib/python3.8/site-packages/mmdet3d-0.17.1-py3.8-linux-x86_64.egg/mmdet3d/models/builder.py", line 57, in build_detector
    return DETECTORS.build(
  File "/home/user/anaconda3/envs/bevformer/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/user/anaconda3/envs/bevformer/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/user/anaconda3/envs/bevformer/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'bevformer is not in the models registry'

<mmdet version>
------------
mmcv-full               1.4.0
mmdet                   2.14.0
mmdet3d                 0.17.1       /home/user/anaconda3/envs/bevformer/lib/python3.8/site-packages/mmdet3d-0.17.1-py3.8-linux-x86_64.egg
mmsegmentation          0.14.1
mypy-extensions         0.4.3

**Comment by zhiqi-li** [comment]
Hi, the type of  model should be `BEVFormer` rather than `bevformer`.

**Comment by Han-lim** [comment]
Oh, it was my mistake. Thanks for your reply!
