### ISSUE TITLE
No module named 'projects'

### ISSUE THREAD

**Issue by Egbert-518** [fundamentalvision/BEVFormer#128]
I have clone mmdetection3d and BEVFormer repository, and follow the installtion step as [this](https://github.com/fundamentalvision/BEVFormer/blob/master/docs/install.md). My files tree is as follows. 
```
├── BEVFormer
  │   ├── docs
  │   ├── figs
  │   ├── LICENSE
  │   ├── projects
  │   ├── README.md
  │   ├── tools
  │   └── work_dirs
  ├── build
  ├── CITATION.cff
  ├── configs
  ├── data
  │   ├── lyft
  │   ├── nuscenes
  │   ├── s3dis
  │   ├── scannet
  │   └── sunrgbd
  ├── demo
  ├── dist
  ├── docker
  ├── docs
  ├── LICENSE
  ├── MANIFEST.in
  ├── mmdet3d
  ├── mmdet3d.egg-info
  ├── model-index.yml
  ├── README.md
  ├── README_zh-CN.md
  ├── requirements
  ├── requirements.txt
  ├── resources
  ├── setup.cfg
  ├── setup.py
  ├── tests
  ├── tools
  └── work_dirs
```
When I run `python3 ./tools/train.py ./projects/configs/bevformer/bevformer_tiny.py` in the BEVFormer dir, it tells me that
```
projects.mmdet3d_plugin
Traceback (most recent call last):
  File "./tools/train.py", line 259, in <module>
    main()
  File "./tools/train.py", line 137, in main
    from projects.mmdet3d_plugin.bevformer.apis.train import custom_train_model
ModuleNotFoundError: No module named 'projects'
```
Is any error here.  My mmcv-full version is 1.6.2, mmdet is 2.25.3, mmdetection3d is the master branch(r1.0.0.rc5). Maybe this will cause the problem? But I have tried to put the 'projects' folders into the root dir, and everything goes on.

**Comment by Yiir-1** [comment]
do you solve it? i have the same question

**Comment by zhangdi-trying** [comment]
> do you solve it? i have the same question

I got it!  You should change the version of panda, such as pip install pandas=1.4.4. Then you can run python install setup

**Comment by zhiqi-li** [comment]
Hi, please follow this doc https://github.com/fundamentalvision/BEVFormer/blob/master/docs/install.md. 
mmdet3d>=1.0 can not be used.

**Comment by Kerwin0621** [comment]
The version of mmdet3d in my conda environment is 0.17.1, but still has the same issue

**Comment by Bin-ze** [comment]
in tools/train.py 
add:
> sys.path.insert(0, 'PATH/BEVFormer')
issue solve

**Comment by xiaoma-zds** [comment]
> in tools/train.py add:
> 
> > sys.path.insert(0, 'PATH/BEVFormer')
> 
> issue solve

I have the same problem ,can I please ask : where is this code added to the train.py code?

**Comment by Bin-ze** [comment]
add this code in train.py above发自我的 iPhone在 2024年1月16日，15:28，xiaoma-zds ***@***.***> 写道：﻿

in tools/train.py add:

sys.path.insert(0, 'PATH/BEVFormer')

issue solve

I have the same problem ,can I please ask : where is this code added to the train.py code?

**Comment by xiaoma-zds** [comment]
![屏幕截图 2024-03-11 151522](https://github.com/fundamentalvision/BEVFormer/assets/156773021/21bc5e89-d6af-4d61-9677-1c346a534f3f) there
> add this code in train.py above发自我的 iPhone在 2024年1月16日，15:28，xiaoma-zds ***@***.***> 写道：﻿ in tools/train.py add: sys.path.insert(0, 'PATH/BEVFormer') issue solve I have the same problem ,can I please ask : where is this code added to the train.py code? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
