### ISSUE TITLE
ModuleNotFoundError: No module named 'ffrecord'

### ISSUE THREAD

**Issue by querry-q** [fundamentalvision/BEVFormer#164]
This error occurs when you start training or verification:

(bevformer) xwt:/data/xwt/bevformer/mmdetection3d/BEVFormer$ ./tools/dist_train.sh ./projects/configs/bevformer/bevformer_base.py 2
projects.mmdet3d_plugin
projects.mmdet3d_plugin
projects.mmdet3d_plugin
Traceback (most recent call last):
  File "./tools/train.py", line 278, in <module>
    torch.multiprocessing.spawn(main, args=(args,), nprocs=ngpus)
  File "/data/xwt/anaconda3/envs/bevformer/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data/xwt/anaconda3/envs/bevformer/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/data/xwt/anaconda3/envs/bevformer/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/data/xwt/anaconda3/envs/bevformer/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/data/xwt/bevformer/mmdetection3d/BEVFormer/tools/train.py", line 128, in main
    plg_lib = importlib.import_module(_module_path)
  File "/data/xwt/anaconda3/envs/bevformer/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/xwt/bevformer/mmdetection3d/BEVFormer/projects/mmdet3d_plugin/__init__.py", line 5, in <module>
    from .datasets.pipelines import (
  File "/data/xwt/bevformer/mmdetection3d/BEVFormer/projects/mmdet3d_plugin/datasets/pipelines/__init__.py", line 5, in <module>
    from .loading import FFrecordClient, LoadMultiViewImageFromFilesHF
  File "/data/xwt/bevformer/mmdetection3d/BEVFormer/projects/mmdet3d_plugin/datasets/pipelines/loading.py", line 7, in <module>
    from ffrecord import FileReader
ModuleNotFoundError: No module named 'ffrecord'

**Comment by Rickustc** [comment]
I also have this prolem. Do you solve it?
