### ISSUE TITLE
AssertionError: Database version not found: ./data/nuscenes/v1.0-trainval

### ISSUE THREAD

**Issue by ynjiun** [fundamentalvision/BEVFormer#170]
Hi

While I followed the instruction to 

`python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0 --canbus ./data`

I encountered the following error message:

```
v1.0-trainval ./data/nuscenes
Traceback (most recent call last):
  File "tools/create_data.py", line 240, in <module>
    nuscenes_data_prep(
  File "tools/create_data.py", line 72, in nuscenes_data_prep
    nuscenes_converter.create_nuscenes_infos(
  File "/home/paul/pytorch/BEVFormer/tools/data_converter/nuscenes_converter.py", line 51, in create_nuscenes_infos
    nusc = NuScenes(version=version, dataroot=root_path, verbose=True)
  File "/home/paul/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/nuscenes_devkit-1.1.10-py3.8.egg/nuscenes/nuscenes.py", line 62, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: ./data/nuscenes/v1.0-trainval
```

I already downloaded can_bus.zip and unzip it under ./data directory.

Could you please help to see what am I missing? Thank you.

**Comment by doublepoints** [comment]
I have the same question, have you solved  it?

**Comment by chuerpan-hri** [comment]
Try using absolute path instead of relative path
