### ISSUE TITLE
win10安装mmdet3d v0.17.1报错

### ISSUE THREAD

**Issue by raphaelhou25** [fundamentalvision/BEVFormer#172]
win10 按照文档步骤进行安装，所有库包的版本都跟文档中一样，最后一步安装mmdetection3d v0.17.1一直报错没有解决。
报错如下：
 running build_ext
      E:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\utils\cpp_extension.py:305: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'mmdet3d.ops.spconv.sparse_conv_ext' extension
      creating C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38
      creating C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release
      creating C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\mmdet3d
      creating C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\mmdet3d\ops
      creating C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\mmdet3d\ops\spconv
      creating C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\mmdet3d\ops\spconv\src
      Emitting ninja build file C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/7] E:\tool_develop\cuda11.1\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\mmdet3d\ops\spconv\src/maxpool_cuda.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\mmdet3d\ops\spconv\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\torch\csrc\api\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\TH -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\THC "-IE:\tool_develop\cuda11.1\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -IE:\tool_develop\anaconda3\envs\bevformer_v8\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\Include -IE:\tool_develop\MicrosoftVisualStudio2022BuildTools\VC\Tools\MSVC\14.33.31629\include -IE:\tool_develop\MicrosoftVisualStudio2022BuildTools\VC\Auxiliary\VS\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" -c C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\mmdet3d\ops\spconv\src\maxpool_cuda.cu -o C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\mmdet3d\ops\spconv\src/maxpool_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_50,code=compute_50 -gencode=arch=compute_50,code=sm_50
      FAILED: C:/Users/asus/AppData/Local/Temp/pip-install-j9kkp1tu/mmdet3d_7e26acf016624840bafafb0d4d4d00df/build/temp.win-amd64-cpython-38/Release/mmdet3d/ops/spconv/src/maxpool_cuda.obj
      E:\tool_develop\cuda11.1\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\mmdet3d\ops\spconv\src/maxpool_cuda.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\mmdet3d\ops\spconv\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\torch\csrc\api\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\TH -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\THC "-IE:\tool_develop\cuda11.1\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -IE:\tool_develop\anaconda3\envs\bevformer_v8\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\Include -IE:\tool_develop\MicrosoftVisualStudio2022BuildTools\VC\Tools\MSVC\14.33.31629\include -IE:\tool_develop\MicrosoftVisualStudio2022BuildTools\VC\Auxiliary\VS\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" -c C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\mmdet3d\ops\spconv\src\maxpool_cuda.cu -o C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\mmdet3d\ops\spconv\src/maxpool_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_50,code=compute_50 -gencode=arch=compute_50,code=sm_50
      CreateProcess failed: The system cannot find the file specified.
      [2/7] E:\tool_develop\cuda11.1\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\mmdet3d\ops\spconv\src/reordering_cuda.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\mmdet3d\ops\spconv\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\torch\csrc\api\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\TH -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\THC "-IE:\tool_develop\cuda11.1\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -IE:\tool_develop\anaconda3\envs\bevformer_v8\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\Include -IE:\tool_develop\MicrosoftVisualStudio2022BuildTools\VC\Tools\MSVC\14.33.31629\include -IE:\tool_develop\MicrosoftVisualStudio2022BuildTools\VC\Auxiliary\VS\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" -c C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\mmdet3d\ops\spconv\src\reordering_cuda.cu -o C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\mmdet3d\ops\spconv\src/reordering_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_50,code=compute_50 -gencode=arch=compute_50,code=sm_50
      FAILED: C:/Users/asus/AppData/Local/Temp/pip-install-j9kkp1tu/mmdet3d_7e26acf016624840bafafb0d4d4d00df/build/temp.win-amd64-cpython-38/Release/mmdet3d/ops/spconv/src/reordering_cuda.obj
      E:\tool_develop\cuda11.1\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\mmdet3d\ops\spconv\src/reordering_cuda.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\mmdet3d\ops\spconv\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\torch\csrc\api\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\TH -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\THC "-IE:\tool_develop\cuda11.1\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -IE:\tool_develop\anaconda3\envs\bevformer_v8\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\Include -IE:\tool_develop\MicrosoftVisualStudio2022BuildTools\VC\Tools\MSVC\14.33.31629\include -IE:\tool_develop\MicrosoftVisualStudio2022BuildTools\VC\Auxiliary\VS\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" -c C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\mmdet3d\ops\spconv\src\reordering_cuda.cu -o C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\mmdet3d\ops\spconv\src/reordering_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_50,code=compute_50 -gencode=arch=compute_50,code=sm_50
      CreateProcess failed: The system cannot find the file specified.
      [3/7] E:\tool_develop\cuda11.1\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\mmdet3d\ops\spconv\src/indice_cuda.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\mmdet3d\ops\spconv\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\torch\csrc\api\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\TH -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\THC "-IE:\tool_develop\cuda11.1\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -IE:\tool_develop\anaconda3\envs\bevformer_v8\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\Include -IE:\tool_develop\MicrosoftVisualStudio2022BuildTools\VC\Tools\MSVC\14.33.31629\include -IE:\tool_develop\MicrosoftVisualStudio2022BuildTools\VC\Auxiliary\VS\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" -c C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\mmdet3d\ops\spconv\src\indice_cuda.cu -o C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\mmdet3d\ops\spconv\src/indice_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_50,code=compute_50 -gencode=arch=compute_50,code=sm_50
      FAILED: C:/Users/asus/AppData/Local/Temp/pip-install-j9kkp1tu/mmdet3d_7e26acf016624840bafafb0d4d4d00df/build/temp.win-amd64-cpython-38/Release/mmdet3d/ops/spconv/src/indice_cuda.obj
      E:\tool_develop\cuda11.1\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\mmdet3d\ops\spconv\src/indice_cuda.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\mmdet3d\ops\spconv\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\torch\csrc\api\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\TH -IE:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\include\THC "-IE:\tool_develop\cuda11.1\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -IE:\tool_develop\anaconda3\envs\bevformer_v8\include -IE:\tool_develop\anaconda3\envs\bevformer_v8\Include -IE:\tool_develop\MicrosoftVisualStudio2022BuildTools\VC\Tools\MSVC\14.33.31629\include -IE:\tool_develop\MicrosoftVisualStudio2022BuildTools\VC\Auxiliary\VS\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" -c C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\mmdet3d\ops\spconv\src\indice_cuda.cu -o C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\build\temp.win-amd64-cpython-38\Release\mmdet3d\ops\spconv\src/indice_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_50,code=compute_50 -gencode=arch=compute_50,code=sm_50
      CreateProcess failed: The system cannot find the file specified.
      ninja: fatal: ReadFile: 句柄无效。

      Traceback (most recent call last):
        File "E:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\utils\cpp_extension.py", line 1666, in _run_ninja_build
          subprocess.run(
        File "E:\tool_develop\anaconda3\envs\bevformer_v8\lib\subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\asus\AppData\Local\Temp\pip-install-j9kkp1tu\mmdet3d_7e26acf016624840bafafb0d4d4d00df\setup.py", line 192, in <module>
          setup(
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\dist.py", line 1221, in run_command
          super().run_command(command)
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "E:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\dist.py", line 1221, in run_command
          super().run_command(command)
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\dist.py", line 1221, in run_command
          super().run_command(command)
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "E:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "E:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\utils\cpp_extension.py", line 709, in build_extensions
          build_ext.build_extensions(self)
        File "E:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
          _build_ext.build_ext.build_extensions(self)
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\asus\AppData\Roaming\Python\Python38\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "E:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\utils\cpp_extension.py", line 682, in win_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "E:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\utils\cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "E:\tool_develop\anaconda3\envs\bevformer_v8\lib\site-packages\torch\utils\cpp_extension.py", line 1682, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmdet3d
  Running setup.py clean for mmdet3d
Failed to build mmdet3d
ERROR: Could not build wheels for mmdet3d, which is required to install pyproject.toml-based projects

**Comment by GWang0122** [comment]
I am encountering the same error. Did you get any updates?
