### ISSUE TITLE
运行./tools/dist_train.sh ./projects/configs/bevformer/bevformer_base.py 2时候报错 ，帮忙看一下。lg_lib = importlib.import_module(_module_path)

### ISSUE THREAD

**Issue by ncepu5** [fundamentalvision/BEVFormer#179]
运行./tools/dist_train.sh ./projects/configs/bevformer/bevformer_base.py 2时候报错 ，帮忙看一下。

lg_lib = importlib.import_module(_module_path)   #这句报错，报错内容如下
------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "./tools/train.py", line 269, in <module>
    main()
  File "./tools/train.py", line 134, in main
    plg_lib = importlib.import_module(_module_path)
  File "/data1/geng.wu/anaconda3/envs/openmmlab/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data4/geng.wu/DataSets/BEVFormer/projects/mmdet3d_plugin/__init__.py", line 5, in <module>
    from .datasets.pipelines import (
  File "/data4/geng.wu/DataSets/BEVFormer/projects/mmdet3d_plugin/datasets/__init__.py", line 1, in <module>
    from .nuscenes_dataset import CustomNuScenesDataset
  File "/data4/geng.wu/DataSets/BEVFormer/projects/mmdet3d_plugin/datasets/nuscenes_dataset.py", line 12, in <module>
    from .nuscnes_eval import NuScenesEval_custom
  File "/data4/geng.wu/DataSets/BEVFormer/projects/mmdet3d_plugin/datasets/nuscnes_eval.py", line 53, in <module>
    from IPython import embed
  File "/data1/geng.wu/anaconda3/envs/openmmlab/lib/python3.8/site-packages/ipython-8.13.2-py3.8.egg/IPython/__init__.py", line 30, in <module>
    raise ImportError(
ImportError:
IPython 8.13+ supports Python 3.9 and above, following NEP 29.
IPython 8.0-8.12 supports Python 3.8 and above, following NEP 29.
When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
Python 3.3 and 3.4 were supported up to IPython 6.x.
Python 3.5 was supported with IPython 7.0 to 7.9.
Python 3.6 was supported with IPython up to 7.16.
Python 3.7 was still supported with the 7.x branch.

See IPython `README.rst` file for more information:

    https://github.com/ipython/ipython/blob/main/README.rst

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 16387) of binary: /data1/geng.wu/anaconda3/envs/openmmlab/bin/python
Traceback (most recent call last):
  File "/data1/geng.wu/anaconda3/envs/openmmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data1/geng.wu/anaconda3/envs/openmmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data1/geng.wu/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/data1/geng.wu/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/data1/geng.wu/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/data1/geng.wu/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/data1/geng.wu/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data1/geng.wu/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
***************************************
        ./tools/train.py FAILED
=======================================
Root Cause:
[0]:
  time: 2023-05-31_16:05:38
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 16387)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************

**Comment by htian01** [comment]
It seems your IPython version is not correct.
