### ISSUE TITLE
请问训练之后，怎么查看结果

### ISSUE THREAD

**Issue by xuefeng1130** [fundamentalvision/BEVFormer#198]
我在v1.0-mini数据集上进行了训练，怎么看实验结果？图表和可视化结果怎么看？

**Comment by xuefeng1130** [comment]
在v1.0-mini上运行visual.py报错

Traceback (most recent call last):
  File "visual.py", line 472, in <module>
    nusc = NuScenes(version='v1.0-mini', dataroot='./data/nuscenes', verbose=True)
  File "/home/axf/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 62, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: ./data/nuscenes/v1.0-mini
