### ISSUE TITLE
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zymard** [fundamentalvision/BEVFormer#233]
(mmlab) taotao@node9:/home/newdisk/sjhcode/bev/BEVFormer$ python tools/create_data.py nuscenes --root-path ../../datasets/nuscenes --out-dir ../../datasets/nuscenes --extra-tag nuscenes --version v1.0 --canbus ../../datasets
Traceback (most recent call last):
  File "tools/create_data.py", line 6, in <module>
    from data_converter.create_gt_database import create_groundtruth_database
  File "/home/newdisk/sjhcode/bev/BEVFormer/tools/data_converter/create_gt_database.py", line 6, in <module>
    from mmcv.ops import roi_align
  File "/home/taotao/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/taotao/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/taotao/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/taotao/anaconda3/envs/mmlab/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

The version of the main library is consistent with the official version

**Comment by lix19937** [comment]
It seems that you has installed torch cpu version.

**Comment by zymard** [comment]
The versions of the environment-related installation packages are as follows:
torch                     1.9.1+cu102              pypi_0    pypi
torchaudio                0.9.1                    pypi_0    pypi
torchvision               0.10.1+cu102             pypi_0    pypi
Thank you for your response. I have upgraded the torch version to torch 1.10.0, avoiding the above error, but I don't know the specific reason.
