### ISSUE TITLE
ModuleNotFoundError: No module named 'tools.data_converter'

### ISSUE THREAD

**Issue by hitbuyi** [fundamentalvision/BEVFormer#237]
When I run command to create data, the error happened 

```
(pt110) hitbuyi@hitbuyi-Dell-G15-5511:~/PycharmProjects/pytorch_project/BEVFormer$ python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0 --canbus ./data
Traceback (most recent call last):
  File "tools/create_data.py", line 10, in <module>
    from data_converter import indoor_converter as indoor
  File "/home/hitbuyi/PycharmProjects/pytorch_project/BEVFormer/tools/data_converter/indoor_converter.py", line 7, in <module>
    from tools.data_converter.s3dis_data_utils import S3DISData, S3DISSegData
ModuleNotFoundError: No module named 'tools.data_converter'
```

my files' hierarchy  as below 

![Screenshot from 2024-03-21 20-22-58](https://github.com/fundamentalvision/BEVFormer/assets/10301777/277e9f6f-fa56-437b-b3bf-04eaf560e112)

What caused this problem and how to solve it ?

**Comment by Aurora-Legend** [comment]
export PYTHONPATH=./

**Comment by lix19937** [comment]
see https://github.com/fundamentalvision/BEVFormer/pull/241#issuecomment-2049094853
